// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBanF3cqUALPa7Uh8Rx2S9ZCm1AEeE0V3Y',
    appId: '1:214810382595:web:e3e0ab1b0b9a17beded936',
    messagingSenderId: '214810382595',
    projectId: 'ping-it-b2e13',
    authDomain: 'ping-it-b2e13.firebaseapp.com',
    storageBucket: 'ping-it-b2e13.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtjUp2eYjFrL3Qo4sCer6aSBsnBGKKLZA',
    appId: '1:214810382595:android:8d84c2645b36cafaded936',
    messagingSenderId: '214810382595',
    projectId: 'ping-it-b2e13',
    storageBucket: 'ping-it-b2e13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1uDtGDSmK6G_BGyF-Rz6uz80ixc99wWI',
    appId: '1:214810382595:ios:639c2531443ede79ded936',
    messagingSenderId: '214810382595',
    projectId: 'ping-it-b2e13',
    storageBucket: 'ping-it-b2e13.appspot.com',
    iosBundleId: 'com.example.pingit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1uDtGDSmK6G_BGyF-Rz6uz80ixc99wWI',
    appId: '1:214810382595:ios:639c2531443ede79ded936',
    messagingSenderId: '214810382595',
    projectId: 'ping-it-b2e13',
    storageBucket: 'ping-it-b2e13.appspot.com',
    iosBundleId: 'com.example.pingit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBanF3cqUALPa7Uh8Rx2S9ZCm1AEeE0V3Y',
    appId: '1:214810382595:web:1419a97e2220e011ded936',
    messagingSenderId: '214810382595',
    projectId: 'ping-it-b2e13',
    authDomain: 'ping-it-b2e13.firebaseapp.com',
    storageBucket: 'ping-it-b2e13.appspot.com',
  );

}